identifier-prefix: icsm.

name: 3D Cadastre Survey Data Exchange Specification

abstract: |
  This resource is a view of the specification for the 3D Cadastral Survey Data (CSD) Exchange Schema. 
 
  The specification is a machine-readable, modular data exchange model using the JSON language, using JSON Schema for structure and a semantic model (JSON-LD and SHACL rules) for more complex constraints. 
  
    **[Implementation profiles](https://icsm-au.github.io/3d-csdm-profiles/)**  with extensive examples are available for Australian and New Zealand jurisdictions.**
  
  The core (top level container) schema can be viewed using the in-built documentation system **[here](bblock/icsm.csdm.features.CSD)** 
  
  The schema re-uses, flexible, standards based components using the [OGC Building Blocks methodology](https://github.com/opengeospatial/bblock-template/blob/master/USAGE.md).  

  The [set of modules comprising the specification](bblock) is implemented as a "register" of "Building Blocks" managed within a [Git repository](https://icsm-au.github.io/3d-csdm-schema/). 
  
  The [documentation for the underlying 3D CSDM](https://icsm-au.github.io/3d-csdm/docs/) data model collates the elements from all the inherited components into a single comprehensive document (directly from the machine-readable sources) 
  
  _Implementation Profiles (e.g. for each Jurisdiction) use the same documentation form extended with specific constraints and vocabulary usages_

description: |
   This specification defines a [JSON schema](https://json-schema.org/) compatible with the [OGC API Features](https://opengeospatial.github.io/e-learning/ogcapi-features/text/basic-main.html) data exchange model.
  
   This schema is linked to the underlying [3D Cadastre Model](https://icsm-au.github.io/3d-csdm/) using JSON-LD, which allows additional constraint rules to be specified using the [SHACL (Shapes Constraint Language) standard](https://www.w3.org/TR/shacl/).

   _The **[REVIEW GUIDE](https://github.com/icsm-au/3d-csdm-profiles/blob/main/REVIEW_GUIDE.md)** provides a detailed overview of all aspects of the design and testing process, and related materials._

   This implementation pattern:
  
   - is supported by the OGC with a set of [open source tools](https://github.com/opengeospatial/bblock-template) and a library of building blocks based on OGC specifications.
   - simplifies development, testing and documentation of each component
   - allows for transparent, machine-readable, identification of the underlying standards each component is based on
   - allows richer machine readable specifications of implementation constraints and controlled vocabulary requirements.
   - supports explicit machine readable profile specifications to support discovery of all the different components required.
 
   The "semantic annotation" capabilities of the OGC Building Block design links the schema to the conceptual and logical models.
   _NB Publication of these models as Linked Data would allow access to documentation of each element by online systems_.

imports:
  - default
  - https://opengeospatial.github.io/ogcapi-sosa/build/register.json
  - https://ogcincubator.github.io/topo-feature/build/register.json
  - https://ogcincubator.github.io/bblock-prov-schema/build/register.json

